###
# @name Post customer1
POST https://localhost:8010/banking/v2/customers
Content-Type: application/json
Accept: application/json

{
  "id": "10000000-0000-0000-0000-000000000000",
  "firstname": "Erika",
  "lastname": "Mustermann",
  "companyName": null,
  "email": "erika.mustermann@t-online.de",
  "subject": "a00090ad-d9df-486a-8757-4a649e26a54e",
  "statusInt": 1,
  "addressDto": {
    "street": "Hauptstr. 23",
    "postalCode": "29556",
    "city": "Suderburg",
    "country": "DE"
  },
  "accountid": "01000000-0000-0000-0000-000000000000",
  "iban": "DE10 1000 0000 0000 0000 42",
  "balance": 2100.0
}
